// @ts-check
/* eslint boundaries/dependencies: off -- The SSR import is generated by the Web build. */
/**
 * The shared frontend entry, mounted by composition through Router.
 *
 * The framework's build produces a fetch handler for the pages and a directory of client files, and
 * neither is served on its own: static files first, then the handler for anything that is a page.
 *
 * The site's address is captured at construction. TypeScript checks this JavaScript entry through
 * JSDoc. Its HTTP adapter wraps the framework's handler and stays local to this module.
 */
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { serveStatic } from '@hono/node-server/serve-static';
import { Hono } from 'hono';

import entry from '../dist/server/server.js';

/**
 * Absolute, on purpose. `serveStatic` resolves a relative root against the working directory, and
 * the composer starts the process from wherever it likes. Measured on `@hono/node-server` 2.0.11:
 * from another working directory a relative root answers 404 with a warning, an absolute one 200.
 */
const CLIENT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '../dist/client');

/**
 * The public pages, in the order a person would meet them. The application and the admin panel are
 * behind sign-in and have nothing to offer a crawler; the legal pages stay out until a project
 * writes them and they say something.
 */
const SITEMAP = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/about', changefreq: 'monthly', priority: '0.7' },
  { path: '/contact', changefreq: 'monthly', priority: '0.5' },
];

/**
 * Builds the site application. It listens to nothing; the composer owns the port.
 *
 * @param {{ origin: string }} settings — captured at construction.
 */
export function createPublicFetch({ origin }) {
  const base = origin.replace(/\/+$/, '');
  const app = new Hono();

  app.get('/robots.txt', (context) =>
    context.text(
      [
        '# Приложение и админка находятся за входом, индексировать там нечего.',
        'User-agent: *',
        'Disallow: /app/',
        'Disallow: /admin/',
        'Disallow: /module/',
        'Allow: /',
        '',
        `Sitemap: ${base}/sitemap.xml`,
        '',
      ].join('\n'),
      200,
      { 'cache-control': 'public, max-age=3600' },
    ),
  );

  app.get('/sitemap.xml', (context) => {
    const entries = SITEMAP.map(
      ({ path, changefreq, priority }) =>
        `  <url>\n` +
        `    <loc>${base}${path}</loc>\n` +
        `    <changefreq>${changefreq}</changefreq>\n` +
        `    <priority>${priority}</priority>\n` +
        `  </url>`,
    ).join('\n');

    return context.body(
      `<?xml version="1.0" encoding="UTF-8"?>\n` +
        `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`,
      200,
      { 'content-type': 'application/xml; charset=utf-8', 'cache-control': 'public, max-age=3600' },
    );
  });

  // Hashed build assets are immutable; public files keep their names and expire sooner.
  // Set the header on the returned Response: serveStatic's onFound runs after creating it.
  const serveClientFiles = serveStatic({ root: CLIENT_ROOT });
  app.use('/*', async (context, next) => {
    const response = await serveClientFiles(context, async () => undefined);
    if (response) {
      response.headers.set('cache-control', context.req.path.startsWith('/assets/')
        ? 'public, max-age=31536000, immutable'
        : 'public, max-age=300');
      return response;
    }
    return next();
  });

  // Assets never become HTML, including extensionless files and source maps.
  app.all('/assets', (context) => context.notFound());
  app.all('/assets/*', (context) => context.notFound());

  // Keep the canonical product entrance and its query string.
  app.get('/app', (context) => context.redirect(`/app/${new URL(context.req.url).search}`));

  // Public pages are SSR; /app receives the shared document and hydrates its client-only branch.
  app.all('/*', async (context) => {
    const response = await entry.fetch(context.req.raw);
    if (context.req.path.startsWith('/app/')) {
      response.headers.set('cache-control', 'no-store');
      response.headers.set('x-robots-tag', 'noindex');
    }
    return response;
  });

  return (/** @type {Request} */ request) => app.fetch(request);
}
