/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteAboutRouteImport } from './routes/_site/about'
import { Route as SiteContactRouteImport } from './routes/_site/contact'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppConfirmEmailChangeRouteImport } from './routes/app.confirm-email-change'
import { Route as AppLoginRouteImport } from './routes/app.login'
import { Route as AppRegisterRouteImport } from './routes/app.register'
import { Route as AppResetPasswordRouteImport } from './routes/app.reset-password'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppVerifyEmailRouteImport } from './routes/app.verify-email'
import { Route as SiteLegalPrivacyRouteImport } from './routes/_site/legal/privacy'
import { Route as SiteLegalTermsRouteImport } from './routes/_site/legal/terms'
import { Route as AppResetPasswordConfirmRouteImport } from './routes/app.reset-password_.confirm'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfirmEmailChangeRoute = AppConfirmEmailChangeRouteImport.update({
  id: '/confirm-email-change',
  path: '/confirm-email-change',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppResetPasswordRoute = AppResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVerifyEmailRoute = AppVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AppRoute,
} as any)
const SiteLegalPrivacyRoute = SiteLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteLegalTermsRoute = SiteLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => SiteRoute,
} as any)
const AppResetPasswordConfirmRoute = AppResetPasswordConfirmRouteImport.update({
  id: '/reset-password_/confirm',
  path: '/reset-password/confirm',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/app/confirm-email-change': typeof AppConfirmEmailChangeRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/verify-email': typeof AppVerifyEmailRoute
  '/app/': typeof AppIndexRoute
  '/legal/privacy': typeof SiteLegalPrivacyRoute
  '/legal/terms': typeof SiteLegalTermsRoute
  '/app/reset-password/confirm': typeof AppResetPasswordConfirmRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/contact': typeof SiteContactRoute
  '/app/confirm-email-change': typeof AppConfirmEmailChangeRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/verify-email': typeof AppVerifyEmailRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
  '/legal/privacy': typeof SiteLegalPrivacyRoute
  '/legal/terms': typeof SiteLegalTermsRoute
  '/app/reset-password/confirm': typeof AppResetPasswordConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/contact': typeof SiteContactRoute
  '/app/confirm-email-change': typeof AppConfirmEmailChangeRoute
  '/app/login': typeof AppLoginRoute
  '/app/register': typeof AppRegisterRoute
  '/app/reset-password': typeof AppResetPasswordRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/verify-email': typeof AppVerifyEmailRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
  '/_site/legal/privacy': typeof SiteLegalPrivacyRoute
  '/_site/legal/terms': typeof SiteLegalTermsRoute
  '/app/reset-password_/confirm': typeof AppResetPasswordConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/about'
    | '/contact'
    | '/app/confirm-email-change'
    | '/app/login'
    | '/app/register'
    | '/app/reset-password'
    | '/app/settings'
    | '/app/verify-email'
    | '/app/'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/reset-password/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/contact'
    | '/app/confirm-email-change'
    | '/app/login'
    | '/app/register'
    | '/app/reset-password'
    | '/app/settings'
    | '/app/verify-email'
    | '/'
    | '/app'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/reset-password/confirm'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/_site/about'
    | '/_site/contact'
    | '/app/confirm-email-change'
    | '/app/login'
    | '/app/register'
    | '/app/reset-password'
    | '/app/settings'
    | '/app/verify-email'
    | '/_site/'
    | '/app/'
    | '/_site/legal/privacy'
    | '/_site/legal/terms'
    | '/app/reset-password_/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/confirm-email-change': {
      id: '/app/confirm-email-change'
      path: '/confirm-email-change'
      fullPath: '/app/confirm-email-change'
      preLoaderRoute: typeof AppConfirmEmailChangeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/register': {
      id: '/app/register'
      path: '/register'
      fullPath: '/app/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reset-password': {
      id: '/app/reset-password'
      path: '/reset-password'
      fullPath: '/app/reset-password'
      preLoaderRoute: typeof AppResetPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verify-email': {
      id: '/app/verify-email'
      path: '/verify-email'
      fullPath: '/app/verify-email'
      preLoaderRoute: typeof AppVerifyEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/legal/privacy': {
      id: '/_site/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof SiteLegalPrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/legal/terms': {
      id: '/_site/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof SiteLegalTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/app/reset-password_/confirm': {
      id: '/app/reset-password_/confirm'
      path: '/reset-password/confirm'
      fullPath: '/app/reset-password/confirm'
      preLoaderRoute: typeof AppResetPasswordConfirmRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteLegalPrivacyRoute: typeof SiteLegalPrivacyRoute
  SiteLegalTermsRoute: typeof SiteLegalTermsRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteLegalPrivacyRoute: SiteLegalPrivacyRoute,
  SiteLegalTermsRoute: SiteLegalTermsRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppConfirmEmailChangeRoute: typeof AppConfirmEmailChangeRoute
  AppLoginRoute: typeof AppLoginRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppResetPasswordRoute: typeof AppResetPasswordRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVerifyEmailRoute: typeof AppVerifyEmailRoute
  AppIndexRoute: typeof AppIndexRoute
  AppResetPasswordConfirmRoute: typeof AppResetPasswordConfirmRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfirmEmailChangeRoute: AppConfirmEmailChangeRoute,
  AppLoginRoute: AppLoginRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppResetPasswordRoute: AppResetPasswordRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVerifyEmailRoute: AppVerifyEmailRoute,
  AppIndexRoute: AppIndexRoute,
  AppResetPasswordConfirmRoute: AppResetPasswordConfirmRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
